# TODO: Try out https://eksworkshop.com/scaling/test_hpa/

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: endpoint-node
  namespace: cloud-phoenix-kata
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: endpoint-node
  metrics:
  - type: Pods
    pods:
      metric:
        name: requests-per-second
      target:
        type: Value
        averageValue: 10
