apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-sh
data:
  backup.sh: |-
    #!/bin/bash
    ARCHIVE_FILE="mongodb.dump.gz"
    S3_BUCKET="fabiocicerchia-base-cloud-phoenix-kata"
    mongodump --uri=$DB_CONNECTION_STRING --gzip --archive=$ARCHIVE_FILE
    aws s3 cp $ARCHIVE_FILE s3://$S3_BUCKET/$ARCHIVE_FILE
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aws-kubectl
            image: expert360/kubectl-awscli:v1.11.2
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: DB_CONNECTION_STRING
            command:
              - /bin/sh
              - -c
            args: ["sh /backup.sh"]
            volumeMounts:
            - name: backup-sh
              mountPath: /backup.sh
              readOnly: true
              subPath: backup.sh
          volumes:
          - name: backup-sh
            configMap:
              name: backup-sh
          restartPolicy: OnFailure
