apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: endpoint-ingress
  namespace: cloud-phoenix-kata
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        backend:
          serviceName: endpoint-node
          servicePort: 80
      - path: /(crash|generatecert)
        backend:
          serviceName: dummy
          servicePort: 80
