apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
    DB_CONNECTION_STRING: "mongodb://user:secret_password@endpoint-node-mongodb:27017/test_db"
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
